#!/bin/bash

# Script to remove duplicate React imports from JSX files
# This fixes the "React has already been declared" errors caused by Vite's jsxInject

echo "Fixing React import duplicates in JSX files..."

# List of files that need fixing (from the find command output)
files=(
    "src/components/layout/MenuSections/MenuSection.jsx"
    "src/components/layout/RootLayout/RootLayout.jsx"
    "src/components/layout/MenuNavigation/MenuNavigation.jsx"
    "src/components/layout/MenuNavigation/MenuHeader.jsx"
    "src/components/layout/PageLayout/PageLayout.jsx"
    "src/components/features/settings/Settings/SettingsFooter.jsx"
    "src/components/features/settings/Settings/DebugSection.jsx"
    "src/components/features/settings/Settings/PasswordSection.jsx"
    "src/components/features/settings/Settings/LanguageSection.jsx"
    "src/components/features/settings/Settings/ThemeSection.jsx"
    "src/components/features/settings/Settings/DeleteAccountModal.jsx"
    "src/components/features/auth/NameInput/Forms/SignupForm.jsx"
    "src/components/features/auth/NameInput/Validation/PasswordStrength.jsx"
    "src/components/features/admin/AdminDashboard/Management/LessonManagement.jsx"
    "src/components/features/admin/AdminDashboard/Management/UserManagement.jsx"
    "src/components/features/admin/AdminDashboard/Management/FeedbackManagement.jsx"
    "src/components/features/game/LevelGuess/LevelSelector.jsx"
    "src/components/features/game/LevelGuess/LevelGuessHeader.jsx"
    "src/components/features/game/PlacementFeedback/Components/FeedbackSummary.jsx"
    "src/components/features/game/PlacementFeedback/PlacementFeedback.jsx"
    "src/components/features/game/LevelGame/LevelGameControls.jsx"
    "src/components/features/game/LevelGame/LevelGameFeedback.jsx"
    "src/components/features/game/LevelGame/LevelGameWords.jsx"
    "src/components/features/game/LevelGame/LevelGameFooter.jsx"
    "src/components/features/game/LevelGame/LevelGameInput.jsx"
    "src/components/features/game/LevelGame/LevelGameStatus.jsx"
    "src/components/features/game/LevelGame/LevelGameHeader.jsx"
    "src/components/features/game/LevelGame/LevelGameInstructions.jsx"
    "src/components/features/game/PlacementTest/PlacementTestHeader.jsx"
    "src/components/features/game/PlacementTest/PlacementQuestion.jsx"
    "src/components/features/game/PlacementTest/PlacementControls.jsx"
    "src/components/features/game/LevelUpTest/LevelUpTestResult.jsx"
    "src/components/features/game/LevelUpTest/LevelUpTestHeader.jsx"
    "src/components/features/game/LevelUpTest/LevelUpTestStages.jsx"
    "src/components/features/profile/Profile/ProfileHeader.jsx"
    "src/components/features/profile/Profile/ProfileActions.jsx"
    "src/components/features/profile/Profile/ProfileControls.jsx"
    "src/components/features/profile/ProfileStats/ProfileStatsFooter.jsx"
    "src/components/features/profile/ProfileStats/ProfileStatsHeader.jsx"
    "src/components/features/profile/ProfileStats/ProfileStatsTable.jsx"
    "src/components/features/support/About/AboutHeader.jsx"
    "src/components/features/support/About/AboutContent.jsx"
    "src/components/features/support/Support/SupportForm.jsx"
    "src/components/features/support/Support/Support.jsx"
    "src/components/features/support/Support/SupportHeader.jsx"
    "src/components/features/support/TermsOfService/TermsHeader.jsx"
    "src/components/features/support/TermsOfService/TermsForm.jsx"
    "src/components/features/ai/AIFeedback/AIFeedbackContent.jsx"
    "src/components/features/ai/AIFeedback/AIFeedbackFooter.jsx"
    "src/components/features/ai/AIReading/AIReadingSetup.jsx"
    "src/components/features/ai/AIReading/AIReadingError.jsx"
    "src/components/features/ai/AIReading/AIReadingProgress.jsx"
    "src/components/features/ai/AIReading/AIReadingContent.jsx"
    "src/components/features/ai/AIReading/AIReadingHeader.jsx"
    "src/components/features/ai/AIReading/AIReadingFooter.jsx"
    "src/components/features/ai/AIWeaknessLesson/AIWeaknessLessonFooter.jsx"
    "src/components/features/ai/AIWeaknessLesson/AIWeaknessLessonHeader.jsx"
    "src/components/features/ai/AIWeaknessLesson/AIWeaknessLessonContent.jsx"
    "src/components/features/ai/AIWeaknessLesson/AIWeaknessLessonProgress.jsx"
    "src/components/features/ai/AIExercise/AIExercise.jsx"
    "src/components/features/ai/AIExercise/Navigation/ExerciseNavigation.jsx"
    "src/components/features/ai/AIExercise/Vocab/VocabModal.jsx"
    "src/components/features/ai/AIExercise/Exercise/ExerciseItem.jsx"
    "src/components/features/ai/AIExercise/Submission/SubmissionProgress.jsx"
    "src/components/features/lessons/GrammarMap/GrammarMapHeader.jsx"
    "src/components/features/lessons/GrammarMap/GrammarMapVisualization.jsx"
    "src/components/features/lessons/LessonEditor/Toolbar/EditorToolbar.jsx"
    "src/components/features/lessons/Lessons/LessonsFooter.jsx"
    "src/components/features/lessons/Lessons/LessonsHeader.jsx"
    "src/components/features/lessons/Lessons/LessonCard.jsx"
    "src/components/features/lessons/Lessons/LessonsLoading.jsx"
    "src/components/features/lessons/Lessons/LessonsList.jsx"
    "src/components/features/lessons/TopicMemory/TopicMemoryMobileCards.jsx"
    "src/components/features/lessons/TopicMemory/TopicMemoryWeaknesses.jsx"
    "src/components/features/lessons/TopicMemory/TopicMemoryTable.jsx"
    "src/components/features/lessons/TopicMemory/TopicMemoryHeader.jsx"
    "src/components/features/lessons/TopicMemory/TopicMemoryFilters.jsx"
    "src/components/features/lessons/TopicMemory/TopicMemoryClearModal.jsx"
    "src/components/features/lessons/TopicMemory/TopicMemoryFooter.jsx"
    "src/components/features/lessons/TopicMemory/TopicMemoryMobileFilters.jsx"
    "src/components/features/vocabulary/VocabDetailModal/VocabDetailModal.jsx"
    "src/components/features/vocabulary/VocabDetailModal/Components/VocabDetails.jsx"
    "src/components/features/vocabulary/Translator/TranslatorFooter.jsx"
    "src/components/features/vocabulary/Translator/TranslationForm.jsx"
    "src/components/features/vocabulary/Translator/TranslatorHeader.jsx"
    "src/components/features/vocabulary/Translator/TranslationFeedback.jsx"
    "src/components/features/vocabulary/VocabTrainer/VocabCard.jsx"
    "src/components/features/vocabulary/VocabTrainer/VocabTrainerFooter.jsx"
    "src/components/features/vocabulary/VocabTrainer/VocabTrainerHeader.jsx"
    "src/components/features/vocabulary/Vocabulary/VocabularyList.jsx"
    "src/components/features/vocabulary/Vocabulary/VocabularyModal.jsx"
    "src/components/features/vocabulary/Vocabulary/VocabularyFooter.jsx"
    "src/components/features/vocabulary/Vocabulary/VocabularyFilter.jsx"
    "src/components/features/vocabulary/Vocabulary/VocabularyHeader.jsx"
    "src/components/common/TextToSpeechBox/Components/PlayButton.jsx"
    "src/components/common/TextToSpeechBox/TextToSpeechBox.jsx"
    "src/components/common/FeedbackBlock/Components/FeedbackAlternatives.jsx"
    "src/components/common/FeedbackBlock/Components/FeedbackDifference.jsx"
    "src/components/common/PrettyFeedback/Components/FeedbackSection.jsx"
    "src/components/common/PrettyFeedback/PrettyFeedback.jsx"
    "src/components/Lesson/LessonContent.jsx"
    "src/components/Lesson/LessonProgress.jsx"
    "src/components/Lesson/LessonHeader.jsx"
    "src/components/Lesson/LessonFooter.jsx"
    "src/pages/Core/ErrorPageView.jsx"
    "src/pages/support/Legal/AboutView.jsx"
)

# Process each file
for file in "${files[@]}"; do
    if [ -f "$file" ]; then
        echo "Processing: $file"
        # Remove lines that start with "import React from" (with any quote style)
        sed -i '' '/^import React from/d' "$file"
    else
        echo "Warning: File not found: $file"
    fi
done

echo "React import cleanup completed!"
