version: '3.9'
services:
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"

  backend:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./backend:/app/backend
    command: >-
      sh -c "pip install -r backend/requirements.txt &&
      python backend/src/utils/setup/migration_script.py &&
      FLASK_ENV=development PYTHONPATH=backend/src python backend/src/app.py"
    ports:
      - "5050:5050"
