version: '3.9'
services:
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"

  backend:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./backend/secrets/.env:/app/secrets/.env
    env_file:
      - ./backend/secrets/.env
    command: >-
      sh -c "export PYTHONDONTWRITEBYTECODE=1 &&
      pip install -r requirements.txt &&
      python src/app/migration_script.py &&
      FLASK_ENV=development PYTHONPATH=src python src/app.py"


    ports:
      - "5050:5050"

