services:
  - type: web
    name: german-class-tool
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: VITE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: ""  # Empty means use relative URLs (required!)
