services:
  - type: web
    name: german-class-tool
    env: python
    envVars:
      - key: DEEPL_API_KEY
        fromFile: /etc/secrets/DEEPL_API_KEY
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
