services:
  - type: web
    name: XploreED
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: VITE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: ""  # Empty means use relative URLs (required!)
      - key: REDIS_HOST
        value: redis
      - key: DB_FILE
        value: /app/database/user_data.db
    dependsOn:
      - redis
  - type: redis
    name: redis
    plan: free
