services:
  - type: web
    name: german-class-tool
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DEEPL_API_KEY
        fromFile: /etc/secrets/DEEPL_API_KEY
